started working with routes
ThatCoderMan/AlfaBankHackathon pull request #13
Opened 2024-01-21 21:20 UTC by VladislavCR

2024-01-21 21:35 UTC, ThatCoderMan requested changes
1. Давай разделим логику по отдельным файлам внутри `enpoints`. 
Внутри `router` будем подключать необходимые роутеры
```python
from app.api.v1.enpoints import pdp_router

api_router = APIRouter()
api_router.include_router(pdp_router, prefix="/dpd")
```
2. Давай роутеры назовём просто router. Потом проимпортируем их в `__init__.py` и уже дадим название
```python
flake8: ignore
from app.api.v1.enpoints.pdp import router as pdp_router
...
```

2024-01-21 21:43 UTC, ThatCoderMan requested changes
нужно ещё 2 эндпоинта на получения списка типов и статусов задач

2024-01-21 21:43 UTC, ThatCoderMan commented on app/api/v1/routers.py
> +@api_v1_router.post('/creating_request/')
нет необходимости, будет проходить на этот эндпоинт `@api_v1_router.post('pdp/{pdp_id}/{task_id}/')`

2024-01-22 17:20 UTC, inferno681 reviewed
Может сделаем одинаковую структуру везде? Либо везде user, либо employee

2024-01-22 18:40 UTC, ThatCoderMan commented
> Может сделаем одинаковую структуру везде? Либо везде user, либо employee

это именно работа руководителем над его сотрудниками. Потом может добавятся функции для работы над ними (назначить другому руководителю и тп)

2024-01-22 18:45 UTC, inferno681 approved these changes

2024-01-22 20:10 UTC, ThatCoderMan approved these changes

2024-01-22 20:10 UTC, merged