Feature/validation
ThatCoderMan/AlfaBankHackathon pull request #21
Opened 2024-01-26 17:04 UTC by inferno681

Убрал константы в отдельный файл в core. Добавил валидацию в схемы

2024-01-26 20:56 UTC, ThatCoderMan requested changes
- У полей `_id` по стандарту поставь 1, добавь условие что поле >1. 
 - У полей в схемах `update` нужно проставлять `= None` или `Field(None,...)` , что бы была возможность изменять не все поля

2024-01-26 20:56 UTC, ThatCoderMan commented on app/models/__init__.py
> +from .pdp import LENGTH_LIMITS_STRING_FIELDS, PDP
зачем нам `LENGTH_LIMITS_STRING_FIELDS`?

2024-01-26 20:56 UTC, ThatCoderMan commented on app/schemas/task.py
> +    type_id: int = 0
= 1, индекса нулевого быть не может. + Нужно проверить, что число >= 1 (так во всех полях `_id`)

2024-01-26 20:56 UTC, ThatCoderMan commented on app/schemas/task.py
> +    type_id: int | None
если мы не будем проставлять = None, то мы не сможем изменить только одно поле, он потребует ввести все

2024-01-26 20:56 UTC, ThatCoderMan commented on app/schemas/pdp.py
добавь обязательное поле цели

2024-01-26 20:56 UTC, ThatCoderMan commented on app/schemas/task.py
> +    deadline: date = Field(min_value=date.today())
не обязательное поле (базу потом подправим)

2024-01-26 20:56 UTC, ThatCoderMan commented on app/schemas/task.py
>      description: str | None
обязательное поле

2024-01-27 15:08 UTC, inferno681 commented on app/schemas/pdp.py
Это поле наследуется.

2024-01-27 18:51 UTC, ThatCoderMan requested changes

2024-01-27 18:51 UTC, ThatCoderMan commented on app/schemas/pdp.py
> +    user_id: int = 1
здесь тоже `PositiveInt`, но по умолчанию id первого пользователя ставить не надо 
(убери `=1`)

2024-01-27 18:51 UTC, ThatCoderMan commented on app/schemas/pdp.py
> +    user_id: PositiveInt = 1
По умолчанию id первого пользователя ставить не надо
(убери =1)

2024-01-27 18:51 UTC, ThatCoderMan commented on app/schemas/task.py
> +    status_id: PositiveInt | None = 1
В обновлении `=1` ставить не нужно, тут указываем `=None`, иначе если мы не передадим это поле, статут поменяется на `не определён`

2024-01-27 19:10 UTC, ThatCoderMan approved these changes

2024-01-27 19:10 UTC, merged