Feature/exeptions
ThatCoderMan/AlfaBankHackathon pull request #27
Opened 2024-01-31 06:33 UTC by inferno681

Сделаны пермишены и организованы константы

2024-01-31 14:45 UTC, ThatCoderMan requested changes
давай эксепшены вынесем в отдельный файл и припишем так
```python
class CRUDNotFoundException(HTTPException):
    def __init__(self, model, pk):
        super().__init__(status_code=status.HTTP_404_NOT_FOUND,
                         detail=f'{model.__tablename__}[{pk}] not found')
```

2024-01-31 14:45 UTC, ThatCoderMan commented on app/crud/user.py
> +    @staticmethod
давай не будем выносить в staticmethod, а сделаем как в остальных методах

2024-01-31 14:45 UTC, ThatCoderMan commented on app/core/constants.py
> +
можно или комментариями отделить логику, что к чему относится, либо разнести по файлам: константы; эксепшены; swagger схемы

2024-01-31 14:45 UTC, ThatCoderMan commented on app/api/v1/endpoints/task.py
> +    dependencies=[Depends(current_user)]
у нас проверка вызовется при `user: User = Depends(current_user)`

2024-01-31 14:45 UTC, ThatCoderMan commented on app/core/constants.py
> +
лучше комментами отделить как в Django settings, нагромождать файлы не надо пожалуй

2024-01-31 15:07 UTC, inferno681 commented
Эксепшны в процессе

2024-02-01 05:57 UTC, ThatCoderMan approved these changes

2024-02-01 05:57 UTC, merged